const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const SUPABASE_URL='https://cnncldeuhpmmkeqqoxjl.supabase.co';
const SUPABASE_KEY='sb_publishable_m5p3SRptQmFlG_cYevMr_w_Z6BWNbea';
const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const publicTeam=[
{name:'Administrador do Sistema',role:'Administrador',email:'admin@escola.pr.gov.br',course:'Gestão completa'},
{name:'Direção da Escola',role:'Diretor',email:'diretor@escola.pr.gov.br',course:'Alimentação, horários e comunicados'},
{name:'Coordenação do Curso',role:'Coordenador',email:'coordenacao@escola.pr.gov.br',course:'Equipe docente e turmas'},
{name:'Antonio Carlos',role:'Professor',email:'antonio.ramires.goncalves@escola.pr.gov.br',course:'3º ano',disciplines:'HTML, CSS, JavaScript, Backend e Projetos'}];
const demoSchedule=[{day:'Segunda',start:'07:30',end:'12:00',activity:'Aulas e atividades do curso'},{day:'Terça',start:'07:30',end:'12:00',activity:'Aulas e projetos'},{day:'Quarta',start:'07:30',end:'12:00',activity:'Laboratório de Desenvolvimento'},{day:'Quinta',start:'07:30',end:'12:00',activity:'Programação e tecnologia'},{day:'Sexta',start:'07:30',end:'12:00',activity:'Projetos e atividades integradoras'}];
const demoPosts=[{type:'Informativo',title:'Bem-vindo ao Curso de Desenvolvimento de Sistemas',content:'Espaço público para comunicados, projetos, atividades e notícias de tecnologia.',author:'Direção da Escola'},{type:'Tecnologia',title:'Aprendizagem prática e projetos',content:'Os estudantes desenvolvem soluções utilizando programação, banco de dados, web, hardware e robótica.',author:'Antonio Carlos'}];
let currentUser=null,currentProfile=null,loginMode='admin',users=publicTeam.map(x=>({...x}));
function showMsg(t,ok=false){const e=$('#loginMsg');if(e){e.textContent=t;e.className=ok?'ok':''}}
function slot(x){return `<div class="slot"><b>${esc(x.day)}</b><span>${esc(x.start)} – ${esc(x.end)}</span><span>${esc(x.activity)}</span></div>`}
function postCard(x){return `<article class="post"><span class="type">${esc(x.type)}</span><h3>${esc(x.title)}</h3><p>${esc(x.content)}</p><small>Publicado por ${esc(x.author||'Equipe escolar')}</small></article>`}
async function load(){await renderSchedule();await renderPosts();renderUsers(users);const {data:{session}}=await sb.auth.getSession();if(session)await restoreSession()}
function renderUsers(list){$('#users').innerHTML=list.map(u=>`<article class="person"><span class="role">${esc(u.role)}</span><strong>${esc(u.full_name||u.name)}</strong><small>${esc(u.disciplines||u.course||'')}</small><small>${esc(u.email||'')}</small></article>`).join('')}
async function renderSchedule(){const {data,error}=await sb.from('schedule').select('*').order('id',{ascending:true});$('#schedule').innerHTML=(!error&&data?.length)?data.map(slot).join(''):demoSchedule.map(slot).join('')}
async function renderPosts(){const {data,error}=await sb.from('posts').select('*').order('created_at',{ascending:false});$('#posts').innerHTML=(!error&&data?.length)?data.map(postCard).join(''):demoPosts.map(postCard).join('')}
function openLogin(){openAdminLogin()}
function openAdminLogin(){loginMode='admin';$('#loginTitle').textContent='Login Administrativo';$('#loginDescription').textContent='Administrador, Diretor, Coordenador e Professor.';$('#loginButton').textContent='Entrar no painel';$('#loginEmail').value='';$('#loginPassword').value='';showMsg('');$('#modal').classList.add('open');$('#panel').hidden=true}
function openStudentLogin(){loginMode='student';$('#loginTitle').textContent='Login do Aluno';$('#loginDescription').textContent='Acesso do aluno às atividades e área de participação.';$('#loginButton').textContent='Entrar como aluno';$('#loginEmail').value='';$('#loginPassword').value='';showMsg('');$('#modal').classList.add('open');$('#panel').hidden=true}
function closeLogin(){$('#modal').classList.remove('open')}
async function restoreSession(){const {data:{user},error}=await sb.auth.getUser();if(error||!user)return;const {data:profile,error:pe}=await sb.from('profiles').select('*').eq('id',user.id).single();if(pe||!profile){await sb.auth.signOut();return}currentUser=user;currentProfile=profile;await loadAuthenticatedUsers();enterPanelFromProfile()}
async function enterPanel(){const email=$('#loginEmail').value.trim(),password=$('#loginPassword').value;if(!email||!password){showMsg('Informe e-mail e senha.');return}$('#loginButton').disabled=true;showMsg('Autenticando...');const {data,error}=await sb.auth.signInWithPassword({email,password});$('#loginButton').disabled=false;if(error){showMsg('Não foi possível entrar. Confira o e-mail e a senha.');return}currentUser=data.user;const {data:profile,error:pe}=await sb.from('profiles').select('*').eq('id',currentUser.id).single();if(pe||!profile){await sb.auth.signOut();showMsg('Usuário autenticado, mas o perfil não foi encontrado.');return}currentProfile=profile;if(loginMode==='admin'&&profile.role==='Aluno'){await sb.auth.signOut();showMsg('Use o Login do Aluno para este usuário.');return}if(loginMode==='student'&&profile.role!=='Aluno'){await sb.auth.signOut();showMsg('Use o Login Administrativo para este perfil.');return}showMsg('Login realizado com sucesso.',true);await loadAuthenticatedUsers();enterPanelFromProfile()}
async function loadAuthenticatedUsers(){const {data,error}=await sb.from('profiles').select('id,full_name,role,email,course,year,disciplines').order('role');if(!error&&data){users=data;renderUsers(data)}}
function enterPanelFromProfile(){const u=currentProfile;if(!u)return;const p=$('#panel');p.hidden=false;let html=`<div class="panel"><p><b>${esc(u.full_name)}</b> • ${esc(u.role)}</p><button class="secondary-btn" onclick="logout()">Sair</button>`;
if(u.role==='Aluno')html+=`<div class="admin-actions"><h3>Área do aluno</h3><p>Bem-vindo! Consulte comunicados, horários e participe das atividades.</p><a class="cta" href="#aluno" onclick="closeLogin()">Participar de uma atividade</a></div>`;
if(u.role==='Administrador')html+=`<div class="admin-actions"><h3>Gerenciar hierarquia</h3>${users.map(x=>`<label>${esc(x.full_name)} — <select onchange="changeRole('${x.id}',this.value)"><option ${x.role==='Administrador'?'selected':''}>Administrador</option><option ${x.role==='Diretor'?'selected':''}>Diretor</option><option ${x.role==='Coordenador'?'selected':''}>Coordenador</option><option ${x.role==='Professor'?'selected':''}>Professor</option><option ${x.role==='Aluno'?'selected':''}>Aluno</option></select></label>`).join('')}</div>`;
if(['Diretor','Administrador','Professor'].includes(u.role))html+=`<div class="admin-actions"><h3>Publicar informação</h3><input id="ptitle" placeholder="Título"><textarea id="pcontent" placeholder="Recado, informativo, notícia ou atividade"></textarea><button onclick="post('${esc(u.full_name)}','Informativo')">Publicar no frontend</button></div>`;
if(['Diretor','Administrador'].includes(u.role))html+=`<div class="admin-actions"><h3>Adicionar horário</h3><input id="day" placeholder="Dia (ex.: Segunda)"><input id="start" placeholder="Início (ex.: 07:30)"><input id="end" placeholder="Fim (ex.: 12:00)"><input id="activity" placeholder="Funcionamento / atividade"><button onclick="addSchedule()">Salvar horário</button></div>`;
if(['Professor','Administrador','Coordenador'].includes(u.role))html+=`<div class="admin-actions"><h3>${u.role==='Coordenador'?'Coordenação de professores e turmas':'Cadastrar aluno'}</h3><input id="sname" placeholder="Nome do aluno"><input id="semail" type="email" placeholder="E-mail"><select id="syear"><option>1º ano</option><option>2º ano</option><option>3º ano</option></select><button onclick="addStudent('${esc(u.full_name)}')">Cadastrar aluno</button></div>`;
html+='</div>';p.innerHTML=html}
async function changeRole(id,role){if(currentProfile?.role!=='Administrador'){alert('Somente o Administrador pode alterar a hierarquia.');return}const {error}=await sb.from('profiles').update({role}).eq('id',id);if(error){alert('Não foi possível alterar a função: '+error.message);return}await loadAuthenticatedUsers();enterPanelFromProfile();alert('Hierarquia atualizada no Supabase.')}
async function post(author,type){const title=$('#ptitle').value.trim(),content=$('#pcontent').value.trim();if(!title||!content){alert('Preencha título e conteúdo.');return}const {error}=await sb.from('posts').insert({author,type,title,content});if(error){alert('Erro ao publicar: '+error.message);return}await renderPosts();alert('Publicado no Supabase e disponível no frontend.')}
async function addSchedule(){const item={day:$('#day').value.trim(),start:$('#start').value.trim(),end:$('#end').value.trim(),activity:$('#activity').value.trim()};if(Object.values(item).some(v=>!v)){alert('Preencha todos os campos.');return}const {error}=await sb.from('schedule').insert(item);if(error){alert('Erro ao salvar horário: '+error.message);return}await renderSchedule();alert('Horário salvo no Supabase.')}
async function addStudent(by){const item={name:$('#sname').value.trim(),email:$('#semail').value.trim()||null,year:$('#syear').value,course:'Desenvolvimento de Sistemas',registered_by:by};if(!item.name){alert('Informe o nome do aluno.');return}const {error}=await sb.from('students').insert(item);if(error){alert('Erro ao cadastrar aluno: '+error.message);return}$('#sname').value='';$('#semail').value='';alert('Aluno cadastrado no Supabase.')}
async function logout(){await sb.auth.signOut();currentUser=null;currentProfile=null;$('#panel').hidden=true;showMsg('Sessão encerrada.',true)}
$('#studentForm').addEventListener('submit',async e=>{e.preventDefault();const item=Object.fromEntries(new FormData(e.target));const {error}=await sb.from('students').insert({...item,course:'Desenvolvimento de Sistemas'});if(error){$('#studentMsg').textContent='Não foi possível registrar a participação.';return}$('#studentMsg').textContent='Participação registrada com sucesso!';$('#studentMsg').className='ok';e.target.reset();e.target.course.value='Desenvolvimento de Sistemas'});
sb.auth.onAuthStateChange((_event,session)=>{if(!session){currentUser=null;currentProfile=null}});
load();